config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get 'home/index'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :payments, only: [:create] do
    collection do
      get :promocode, as: :promocode
      post :confirm, as: :confirm
      post :enter_promo, as: :enter_promo
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :cover
  has_one_attached :content

  has_many :user_books
  has_many :users, through: :user_books

  validates :title, presence: true,
                    length: { minimum: 2 }


end

app/models/promocode.rb
class Promocode < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  has_many :user_books
  has_many :books, through: :user_books

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_greating

  def send_greating
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end


  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
  
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  
    redirect_to books_path
  end

  private
  def book_params
    if params.dig(:book, :cover)
      image = MiniMagick::Image.new(params[:book][:cover].tempfile.path)
      image.resize "50x50"
    end

    params.require(:book).permit(:title, :author, :cover, :content, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create    
    @book = Book.find(params[:book_id])
    #a = @book.user_books.create(user_id: current_user)  
    @book.users << current_user   
  end

  def promocode
    @book = Book.find(params[:book_id])
  end

  def enter_promo
    @book = Book.find(params[:book_id]) 
    current_user.phone = params[:phone]
    current_user.save

    @promo = Promocode.new(code: create_promocode)
    @promo.save
    puts @promo.code

    render :promocode
  end

  def confirm
    @book = Book.find(params[:book_id])  
    entered_promocode = params[:promocode]
    @promo = Promocode.where(code: entered_promocode).first
    if(@promo)
      @book = Book.find(params[:book_id])
      @book.users << current_user
      current_user.update(free_promo_used: true)
      render "books/show"
    else
      render :false_promo
    end
    #render :promocode
  end

  private
  def create_promocode
    rand(10**5..10**6-1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.erb
<%= form_with(model: @book, local: true) do |form| %> 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :cover %><br>
    <%= form.file_field :cover %>
  </p>
 <p>
    <%= form.label :content %><br>
    <%= form.file_field :content %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/books/edit.erb
<h1>Edit Book</h1>
<%= render 'form' %> 
<%= link_to 'Back', books_path %>

app/views/books/index.erb
<h1>Books</h1> 
 
  <% @books.each do |book| %>
    
      <%if book.cover.attached?%>
       <div class='image'> <img src="<%=(url_for(book.cover))%>"></div>
      <%end%>
      <div class='info'>
       <strong>Title:</strong>
        <%= book.title %><br>
        <strong>Author:</strong>
        <%= book.author %>
        <%= link_to 'Show', book_path(book) %>
        <% if admin_signed_in?%>
          <%= link_to '|Edit', edit_book_path(book) %>
          <%= link_to '|Destroy', book_path(book),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <%end%>
      </div> 
  <% end %>

app/views/books/new.erb
<h1> New book</h1>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.erb
<p>
  <%if @book.cover.attached?%>
    <img src="<%=(url_for(@book.cover))%>">
  <%end%>
</p>

<p>
  <%if @book.content.attached? && admin_signed_in?%>
    <a href="<%=(url_for(@book.content))%>"> Open pdf</a>
  <%end%>
</p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
<p>
  <%if @book.price?%>
   <b class='btn btn-warning'>Price $ <%= @book.price.round(2) %></b>
  <%end%>
</p>
<% if current_user%>
  <% if !current_user.books.include?(@book) %>
    <%if !current_user.free_promo_used%>
      <%= link_to 'Get Free', promocode_payments_path(book_id: @book.id), :class => 'btn btn-secondary'%>
    <%end%>
    <%= link_to 'Buy', payments_path(buy: true, book_id: @book.id), method: :post, :class => 'btn btn-success'%>
  <%else%>
    <b class='btn btn-primary'>You already bought this book.
      <%if @book.content.attached?%>
         <a href="<%=(url_for(@book.content))%>" class='btn btn-warning'> Open pdf</a>
     <%end%>
    </b>
  <%end%>
<%end%> 
<br>
<br>
<% if admin_signed_in?%>
  <%= link_to 'Edit', edit_book_path(@book) %> |
<%end%>
<%= link_to 'Back', books_path %>

app/views/home/index.erb
<h1> HELLO</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <div class="container">
        <a class="navbar-brand" href="/">Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to('Books', books_path) %>
  
              <% if admin_signed_in? %>
                |
                <%= link_to 'New book', new_book_path %>
              <%end %>
            </li>
          </ul>            
          <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>        
          <% elsif admin_signed_in?%>
            Logged in as <strong>Admin <%= current_admin.email %></strong>.
            <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
            <%= link_to "Login as admin", new_admin_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  
    
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/payments/create.erb
<h1> Book bought</h1>

app/views/payments/false_promo.erb
<h1>your promo is false</h1>
<%= link_to 'Back', promocode_payments_path(book_id: @book.id), :class => 'btn btn-secondary'%>

app/views/payments/promocode.erb
<h3>To get the free book, please enter your phone and we will send you a promocode</h3>

<%= form_with(url: enter_promo_payments_path, local: true) do |form| %> 
  <p>
    <%= form.label :phone %><br>
    <%= form.text_field :phone, value: current_user.phone %>
    <%=form.hidden_field :book_id, :value => @book.id %>
  </p>
  <p>
    <%= form.submit("send promo") %>
  </p>
<% end %>

<%= form_with(url: confirm_payments_path, local: true) do |form| %> 
  <p>
    <%= form.label :promocode %><br>
    <%= form.text_field :promocode %>
  </p>
    <%=form.hidden_field :book_id, :value => @book.id %>
    
  <p>
    <%= form.submit('confirm promo') %>
  </p>
<% end %>

app/views/user/profile.erb
hello user